services:
  db:
    image: mysql:8
    container_name: medical-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=medical_app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
    ports:
      - "3307:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
